# Generated by Django 5.2.12 on 2026-05-20 16:03

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_analisis", models.DateField()),
                ("version_carga", models.DecimalField(decimal_places=1, max_digits=4)),
                ("origen", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completo", "Completo"),
                            ("Incompleto", "Incompleto"),
                        ],
                        default="Incompleto",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("creado_en", models.DateTimeField()),
                ("actualizado", models.DateTimeField()),
            ],
            options={
                "db_table": "reliability_acacarga",
                "ordering": ["-fecha_analisis", "-creado_en"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cargo", models.CharField(max_length=150)),
                ("area", models.CharField(max_length=150)),
                ("jefatura", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "reliability_cargo",
                "ordering": ["nombre_cargo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reliability_componente",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("tipo_funcional", models.CharField(max_length=20)),
                ("tipo_dato", models.CharField(max_length=20)),
                (
                    "tipo_calculo",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("config_calculo", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reliability_dimension",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("campo", models.CharField(max_length=120)),
                ("tipo", models.CharField(max_length=20)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "reliability_dimensioncatalogo",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        max_length=50,
                    ),
                ),
                ("logo", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "db_table": "reliability_empresa",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_equipo", models.CharField(max_length=100)),
                ("nombre_equipo", models.CharField(max_length=200)),
                ("ut", models.CharField(max_length=200)),
                ("descripcion_ut", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "reliability_equipo",
                "ordering": ["tag_equipo", "nombre_equipo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalaUnificada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.PositiveIntegerField(unique=True)),
                ("significado", models.CharField(max_length=100)),
                ("interpretacion", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "reliability_escalaunificada",
                "ordering": ["nivel"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metodologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("abreviatura", models.CharField(max_length=20)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reliability_metodologia",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("correo_corporativo", models.EmailField(max_length=254)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        db_column="auth_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="perfil_reliability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cargo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios",
                        to="core.cargo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_column="empresa_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_usuario",
                "ordering": ["nombre_completo"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Criticidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escenario_falla", models.TextField(blank=True)),
                (
                    "frecuencia_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "frecuencia_normalizada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_cons_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("indicador_criticidad", models.CharField(max_length=100)),
                (
                    "valor_criticidad_equipo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("criticidad_final", models.CharField(max_length=30)),
                ("creado_en", models.DateTimeField()),
                (
                    "aca_carga",
                    models.ForeignKey(
                        db_column="aca_carga_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.carga",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="equipo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_criticidad",
                "ordering": ["-creado_en", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoColumna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_columna", models.CharField(max_length=150)),
                ("clave_interna", models.CharField(max_length=100)),
                ("tipo_dato", models.CharField(max_length=20)),
                ("orden", models.PositiveIntegerField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        db_column="catalogo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="columnas",
                        to="core.dimensioncatalogo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogocolumna",
                "ordering": ["catalogo_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoFila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=255)),
                ("orden", models.PositiveIntegerField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        db_column="catalogo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filas",
                        to="core.dimensioncatalogo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogofila",
                "ordering": ["catalogo_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoCelda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                (
                    "columna",
                    models.ForeignKey(
                        db_column="columna_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.dimensioncatalogocolumna",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        db_column="fila_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.dimensioncatalogofila",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogocelda",
                "ordering": ["fila_id", "columna_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComponenteEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "componente",
                    models.ForeignKey(
                        db_column="componente_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="componentes_equipo",
                        to="core.componente",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="componentes",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_componenteequipo",
                "ordering": ["equipo_id", "componente_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Estrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("version", models.DecimalField(decimal_places=1, max_digits=4)),
                ("activa", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="estrategias",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_estrategia",
                "ordering": ["empresa__nombre", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carga",
            name="estrategia",
            field=models.ForeignKey(
                db_column="estrategia_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas",
                to="core.estrategia",
            ),
        ),
        migrations.CreateModel(
            name="EstrategiaDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                ("obligatorio", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "proceso_uso",
                    models.CharField(
                        choices=[
                            ("aca", "ACA"),
                            ("rcm", "RCM"),
                            ("ambos", "ACA y RCM"),
                        ],
                        default="aca",
                        max_length=10,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        db_column="dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="estrategias_dimension",
                        to="core.dimension",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dimensiones_estrategia",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_estrategiadimension",
                "ordering": ["estrategia_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalaValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_ordinal", models.PositiveIntegerField()),
                (
                    "valor_numerico",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=20)),
                (
                    "escala_unificada",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_unificada_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores",
                        to="core.escalaunificada",
                    ),
                ),
                (
                    "estrategia_dimension",
                    models.ForeignKey(
                        db_column="estrategia_dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="escalas_valor",
                        to="core.estrategiadimension",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_escalavalor",
                "ordering": ["estrategia_dimension_id", "nivel_ordinal"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dimensioncatalogo",
            name="estrategia_dimension",
            field=models.OneToOneField(
                db_column="estrategia_dimension_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="catalogo",
                to="core.estrategiadimension",
            ),
        ),
        migrations.CreateModel(
            name="CriticidadDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_numerico",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_secundario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "criticidad",
                    models.ForeignKey(
                        db_column="criticidad_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dimensiones",
                        to="core.criticidad",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        db_column="dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades_dimension",
                        to="core.dimension",
                    ),
                ),
                (
                    "catalogo_fila",
                    models.ForeignKey(
                        blank=True,
                        db_column="catalogo_fila_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.dimensioncatalogofila",
                    ),
                ),
                (
                    "escala_unificada",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_unificada_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.escalaunificada",
                    ),
                ),
                (
                    "escala_valor",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_valor_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.escalavalor",
                    ),
                ),
                (
                    "estrategia_dimension",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_dimension_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.estrategiadimension",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_criticidaddimension",
                "ordering": ["criticidad_id", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatrizRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_creado", models.DateField()),
                ("eje_horizontal", models.CharField(max_length=20)),
                ("leyenda_json", models.TextField(blank=True)),
                (
                    "dimension_impacto",
                    models.ForeignKey(
                        blank=True,
                        db_column="dimension_impacto_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_impacto",
                        to="core.estrategiadimension",
                    ),
                ),
                (
                    "dimension_probabilidad",
                    models.ForeignKey(
                        blank=True,
                        db_column="dimension_probabilidad_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_probabilidad",
                        to="core.estrategiadimension",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_riesgo",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_matrizriesgo",
                "ordering": ["-fecha_creado", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(max_length=255)),
                ("orden_visual", models.PositiveIntegerField()),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="niveles_impacto",
                        to="core.matrizriesgo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_nivelesimpacto",
                "ordering": ["matriz_id", "orden_visual"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelJerarquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="niveles_jerarquia",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_niveljerarquia",
                "ordering": ["empresa__nombre", "orden", "nombre"],
                "abstract": False,
                "unique_together": {("empresa", "nombre"), ("empresa", "orden")},
            },
        ),
        migrations.CreateModel(
            name="NivelProbabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(max_length=255)),
                ("orden_visual", models.PositiveIntegerField()),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="niveles_probabilidad",
                        to="core.matrizriesgo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_nivelesprobabilidad",
                "ordering": ["matriz_id", "orden_visual"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatrizRiesgoCelda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clasificacion", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=20)),
                ("resultado_num", models.DecimalField(decimal_places=2, max_digits=10)),
                ("calcular", models.BooleanField(default=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.matrizriesgo",
                    ),
                ),
                (
                    "impacto_nivel",
                    models.ForeignKey(
                        db_column="impacto_nivel_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.nivelimpacto",
                    ),
                ),
                (
                    "probabilidad",
                    models.ForeignKey(
                        db_column="probabilidad_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.nivelprobabilidad",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_matrizriesgocelda",
                "ordering": ["matriz_id", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NodoJerarquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="nodos_jerarquia",
                        to="core.empresa",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        db_column="nivel_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="nodos",
                        to="core.niveljerarquia",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hijos",
                        to="core.nodojerarquia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_nodojerarquia",
                "ordering": [
                    "empresa__nombre",
                    "nivel__orden",
                    "orden",
                    "codigo",
                    "nombre",
                ],
                "abstract": False,
                "unique_together": {("empresa", "parent", "codigo")},
            },
        ),
        migrations.AddField(
            model_name="equipo",
            name="nodo",
            field=models.ForeignKey(
                blank=True,
                db_column="nodo_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipos",
                to="core.nodojerarquia",
            ),
        ),
        migrations.CreateModel(
            name="PlantillaPauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="plantillas_pautas/")),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_column="empresa_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="plantillas_pauta",
                        to="core.empresa",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="plantillas_pauta",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_plantillapauta",
                "ordering": ["-activa", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MapeoPlantillaPauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hoja_principal", models.CharField(blank=True, max_length=120)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "plantilla",
                    models.OneToOneField(
                        db_column="plantilla_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mapeo",
                        to="core.plantillapauta",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_mapeoplantillapauta",
                "ordering": ["plantilla__nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criticidad", models.IntegerField(blank=True, null=True)),
                ("fecha_analisis", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Completo", "Completo"),
                            ("Incompleto", "Incompleto"),
                        ],
                        default="Incompleto",
                        max_length=20,
                    ),
                ),
                (
                    "componente",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Componente"
                    ),
                ),
                ("falla_funcional", models.TextField()),
                ("modo_de_falla", models.TextField()),
                ("causa", models.TextField(blank=True, null=True)),
                ("efecto", models.TextField()),
                (
                    "carga",
                    models.OneToOneField(
                        db_column="carga_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rcm",
                        to="core.carga",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="registros_rcm",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_rcm",
                "ordering": ["-fecha_analisis", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FMEA_FMECA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rcm",
                    models.OneToOneField(
                        db_column="rcm_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fmea_fmeca",
                        to="core.rcm",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_fmea_fmeca",
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_servicio", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("en_curso", "En curso"),
                            ("cerrado", "Cerrado"),
                            ("pausado", "Pausado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios",
                        to="core.empresa",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_servicio",
                "ordering": ["-creado_en", "codigo_servicio"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReglaGeneracionPauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("agrupar_por_equipo", models.BooleanField(default=True)),
                ("agrupar_por_ubicacion", models.BooleanField(default=True)),
                ("agrupar_por_frecuencia", models.BooleanField(default=True)),
                ("agrupar_por_especialidad", models.BooleanField(default=True)),
                ("agrupar_por_estado_equipo", models.BooleanField(default=True)),
                ("incluir_tareas_primarias", models.BooleanField(default=True)),
                ("incluir_tareas_secundarias", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reglas_pauta",
                        to="core.estrategia",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="servicio_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reglas_pauta",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_reglageneracionpauta",
                "ordering": ["servicio_id", "estrategia_id", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plantillapauta",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                db_column="servicio_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="plantillas_pauta",
                to="core.servicio",
            ),
        ),
        migrations.CreateModel(
            name="Pauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=80)),
                ("nombre", models.CharField(max_length=200)),
                ("area", models.CharField(blank=True, max_length=150)),
                ("ubicacion_tecnica", models.CharField(blank=True, max_length=200)),
                ("frecuencia", models.CharField(blank=True, max_length=150)),
                ("especialidad", models.CharField(blank=True, max_length=100)),
                ("estado_equipo", models.CharField(blank=True, max_length=100)),
                (
                    "estrategia_mantenimiento",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "cantidad_personas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duracion_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hh_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("rcm", "RCM"),
                            ("fmea", "FMEA"),
                            ("manual", "Manual"),
                        ],
                        default="rcm",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("generada", "Generada"),
                            ("revisada", "Revisada"),
                            ("aprobada", "Aprobada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="equipo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pautas",
                        to="core.equipo",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pautas",
                        to="core.estrategia",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        blank=True,
                        db_column="plantilla_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pautas",
                        to="core.plantillapauta",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pautas",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_pauta",
                "ordering": ["-creado_en", "codigo"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carga",
            name="servicio",
            field=models.ForeignKey(
                db_column="servicio_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas",
                to="core.servicio",
            ),
        ),
        migrations.CreateModel(
            name="ServicioEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios_equipo",
                        to="core.equipo",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="equipos_servicio",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_servicioequipo",
                "ordering": ["servicio_id", "equipo_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicioMetodologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodologia",
                    models.ForeignKey(
                        db_column="metodologia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicio_metodologias",
                        to="core.metodologia",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicio_metodologias",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_serviciometodologia",
                "ordering": ["servicio_id", "metodologia_id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="servicio",
            name="metodologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="servicios",
                through="core.ServicioMetodologia",
                to="core.metodologia",
            ),
        ),
        migrations.CreateModel(
            name="TipoTareaEstrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(max_length=80)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tipos_tarea",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_tipo_tarea_estrategia",
                "ordering": ["estrategia_id", "orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TareaRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("tactica", models.CharField(blank=True, max_length=100)),
                ("limite_aceptable", models.TextField(blank=True)),
                ("parametros", models.TextField(blank=True)),
                ("riesgo_material", models.TextField(blank=True)),
                ("especialidad", models.CharField(blank=True, max_length=100)),
                ("puesto_trabajo", models.CharField(blank=True, max_length=100)),
                ("estado_equipo", models.CharField(blank=True, max_length=100)),
                (
                    "frecuencia_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("frecuencia_unidad", models.CharField(blank=True, max_length=50)),
                ("frecuencia_texto", models.CharField(blank=True, max_length=150)),
                (
                    "duracion_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duracion_hr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cantidad_personas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("plan_sap", models.CharField(blank=True, max_length=100)),
                ("descripcion_plan", models.TextField(blank=True)),
                ("hoja_ruta", models.CharField(blank=True, max_length=100)),
                ("texto_hoja_ruta", models.TextField(blank=True)),
                ("operacion_hoja_ruta", models.CharField(blank=True, max_length=100)),
                ("texto_operacion", models.TextField(blank=True)),
                ("operacion_pauta", models.CharField(blank=True, max_length=100)),
                ("pauta", models.CharField(blank=True, max_length=150)),
                ("titulo_pauta", models.TextField(blank=True)),
                ("repuesto", models.TextField(blank=True)),
                ("componente_involucrado", models.TextField(blank=True)),
                ("numero_parte", models.CharField(blank=True, max_length=100)),
                ("numero_sap", models.CharField(blank=True, max_length=100)),
                ("procedimiento_trabajo", models.TextField(blank=True)),
                (
                    "costo_hh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_repuestos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifa_servicios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("oportunidad_mejora", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("reemplazado", "Reemplazado"),
                            ("eliminado", "Eliminado"),
                        ],
                        default="activo",
                        max_length=30,
                    ),
                ),
                (
                    "fmea",
                    models.ForeignKey(
                        db_column="fmea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas_rcm",
                        to="core.fmea_fmeca",
                    ),
                ),
                (
                    "tipo_tarea_estrategia",
                    models.ForeignKey(
                        db_column="tipo_tarea_estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas_rcm",
                        to="core.tipotareaestrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_tarea_rcm",
                "ordering": ["fmea_id", "orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampoTareaEstrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("clave", models.SlugField(max_length=100)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("texto_largo", "Texto largo"),
                            ("numero", "Número entero"),
                            ("decimal", "Número decimal"),
                            ("fecha", "Fecha"),
                            ("booleano", "Sí/No"),
                            ("opcion", "Opción"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                ("opciones_json", models.TextField(blank=True)),
                ("obligatorio", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_tarea_estrategia",
                    models.ForeignKey(
                        db_column="tipo_tarea_estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="campos",
                        to="core.tipotareaestrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_campo_tarea_estrategia",
                "ordering": ["tipo_tarea_estrategia_id", "orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsuarioEliminado",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="archivo_eliminacion",
                        serialize=False,
                        to="core.usuario",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("correo_corporativo", models.EmailField(blank=True, max_length=254)),
                ("eliminado_en", models.DateTimeField()),
                ("motivo", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "reliability_usuario_eliminado",
                "ordering": ["-eliminado_en", "nombre_completo"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="servicio",
            name="creado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por_usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="responsable_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="responsable_usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios_responsables",
                to="core.usuario",
            ),
        ),
        migrations.CreateModel(
            name="InicioSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.DateTimeField()),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inicios_sesion",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_iniciosesion",
                "ordering": ["-hora"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carga",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas",
                to="core.usuario",
            ),
        ),
        migrations.CreateModel(
            name="AccesoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puede_ver", models.BooleanField(default=True)),
                ("puede_editar", models.BooleanField(default=False)),
                ("puede_ver_todo", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.empresa",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.estrategia",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="servicio_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.servicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_accesousuario",
                "ordering": ["-creado_en"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValorCampoTareaRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("valor_fecha", models.DateField(blank=True, null=True)),
                (
                    "campo",
                    models.ForeignKey(
                        db_column="campo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_tarea",
                        to="core.campotareaestrategia",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        db_column="tarea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_campos",
                        to="core.tarearcm",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_valor_campo_tarea_rcm",
                "ordering": ["tarea_id", "campo__orden", "campo_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvaluacionFMEA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_numerico", models.IntegerField(blank=True, null=True)),
                ("valor_texto", models.CharField(blank=True, max_length=255)),
                (
                    "catalogo_fila",
                    models.ForeignKey(
                        blank=True,
                        db_column="catalogo_fila_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluaciones_fmea",
                        to="core.dimensioncatalogofila",
                    ),
                ),
                (
                    "escala_valor",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_valor_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluaciones_fmea",
                        to="core.escalavalor",
                    ),
                ),
                (
                    "estrategia_dimension",
                    models.ForeignKey(
                        db_column="estrategia_dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluaciones_fmea",
                        to="core.estrategiadimension",
                    ),
                ),
                (
                    "fmea",
                    models.ForeignKey(
                        db_column="fmea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluaciones",
                        to="core.fmea_fmeca",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_evaluacionfmea",
                "ordering": ["fmea_id", "estrategia_dimension_id"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["fmea"], name="idx_evalfmea_fmea"),
                    models.Index(
                        fields=["estrategia_dimension"], name="idx_evalfmea_edim"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fmea", "estrategia_dimension"),
                        name="uniq_fmea_dimension",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PautaTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("componente", models.CharField(blank=True, max_length=200)),
                ("actividad", models.TextField()),
                ("limite_aceptable", models.TextField(blank=True)),
                ("observacion", models.TextField(blank=True)),
                (
                    "tipo_tarea",
                    models.CharField(
                        choices=[
                            ("primaria", "Primaria"),
                            ("secundaria", "Secundaria"),
                            ("manual", "Manual"),
                        ],
                        default="primaria",
                        max_length=20,
                    ),
                ),
                ("origen_modelo", models.CharField(blank=True, max_length=80)),
                ("origen_id", models.PositiveIntegerField(blank=True, null=True)),
                ("frecuencia", models.CharField(blank=True, max_length=150)),
                ("pto_trabajo", models.CharField(blank=True, max_length=100)),
                (
                    "cantidad_personas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duracion_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("estado_equipo", models.CharField(blank=True, max_length=100)),
                (
                    "pauta",
                    models.ForeignKey(
                        db_column="pauta_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas",
                        to="core.pauta",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_pautatarea",
                "ordering": ["pauta_id", "orden", "id"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["pauta"], name="idx_ptarea_pauta"),
                    models.Index(fields=["tipo_tarea"], name="idx_ptarea_tipo"),
                    models.Index(
                        fields=["origen_modelo", "origen_id"], name="idx_ptarea_origen"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rcm",
            index=models.Index(fields=["equipo"], name="idx_rcm_equipo"),
        ),
        migrations.AddIndex(
            model_name="rcm",
            index=models.Index(fields=["estado"], name="idx_rcm_estado"),
        ),
        migrations.AddIndex(
            model_name="rcm",
            index=models.Index(fields=["fecha_analisis"], name="idx_rcm_fecha"),
        ),
        migrations.AddIndex(
            model_name="rcm",
            index=models.Index(fields=["criticidad"], name="idx_rcm_criticidad"),
        ),
        migrations.AddIndex(
            model_name="reglageneracionpauta",
            index=models.Index(fields=["estrategia"], name="idx_rgpa_estrategia"),
        ),
        migrations.AddIndex(
            model_name="reglageneracionpauta",
            index=models.Index(fields=["servicio"], name="idx_rgpa_servicio"),
        ),
        migrations.AddIndex(
            model_name="reglageneracionpauta",
            index=models.Index(fields=["activa"], name="idx_rgpa_activa"),
        ),
        migrations.AddIndex(
            model_name="plantillapauta",
            index=models.Index(fields=["empresa"], name="idx_ppauta_empresa"),
        ),
        migrations.AddIndex(
            model_name="plantillapauta",
            index=models.Index(fields=["servicio"], name="idx_ppauta_servicio"),
        ),
        migrations.AddIndex(
            model_name="plantillapauta",
            index=models.Index(fields=["estrategia"], name="idx_ppauta_estrategia"),
        ),
        migrations.AddIndex(
            model_name="plantillapauta",
            index=models.Index(fields=["activa"], name="idx_ppauta_activa"),
        ),
        migrations.AddIndex(
            model_name="pauta",
            index=models.Index(fields=["servicio"], name="idx_pauta_servicio"),
        ),
        migrations.AddIndex(
            model_name="pauta",
            index=models.Index(fields=["estrategia"], name="idx_pauta_estrategia"),
        ),
        migrations.AddIndex(
            model_name="pauta",
            index=models.Index(fields=["equipo"], name="idx_pauta_equipo"),
        ),
        migrations.AddIndex(
            model_name="pauta",
            index=models.Index(fields=["estado"], name="idx_pauta_estado"),
        ),
        migrations.AddIndex(
            model_name="pauta",
            index=models.Index(fields=["origen"], name="idx_pauta_origen"),
        ),
        migrations.AddConstraint(
            model_name="pauta",
            constraint=models.UniqueConstraint(
                fields=("servicio", "codigo"), name="uniq_pauta_servicio_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["estrategia"], name="idx_tte_estrategia"),
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["codigo"], name="idx_tte_codigo"),
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["activo"], name="idx_tte_activo"),
        ),
        migrations.AddConstraint(
            model_name="tipotareaestrategia",
            constraint=models.UniqueConstraint(
                fields=("estrategia", "codigo"), name="uniq_tte_estrategia_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["fmea"], name="idx_trcm_fmea"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(
                fields=["tipo_tarea_estrategia"], name="idx_trcm_tipo_estrat"
            ),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["estado"], name="idx_trcm_estado"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["plan_sap"], name="idx_trcm_plan_sap"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["hoja_ruta"], name="idx_trcm_hoja_ruta"),
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(
                fields=["tipo_tarea_estrategia"], name="idx_cte_tipo_tarea"
            ),
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(fields=["clave"], name="idx_cte_clave"),
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(fields=["activo"], name="idx_cte_activo"),
        ),
        migrations.AddConstraint(
            model_name="campotareaestrategia",
            constraint=models.UniqueConstraint(
                fields=("tipo_tarea_estrategia", "clave"), name="uniq_cte_tipo_clave"
            ),
        ),
        migrations.AddField(
            model_name="usuarioeliminado",
            name="auth_user",
            field=models.ForeignKey(
                blank=True,
                db_column="auth_user_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios_eliminados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuarioeliminado",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                db_column="cargo_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios_eliminados",
                to="core.cargo",
            ),
        ),
        migrations.AddField(
            model_name="usuarioeliminado",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="eliminado_por_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="eliminaciones_de_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuarioeliminado",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                db_column="empresa_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios_eliminados",
                to="core.empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="valorcampotarearcm",
            index=models.Index(fields=["tarea"], name="idx_vctr_tarea"),
        ),
        migrations.AddIndex(
            model_name="valorcampotarearcm",
            index=models.Index(fields=["campo"], name="idx_vctr_campo"),
        ),
        migrations.AddConstraint(
            model_name="valorcampotarearcm",
            constraint=models.UniqueConstraint(
                fields=("tarea", "campo"), name="uniq_valor_tarea_campo"
            ),
        ),
    ]
