# Generated by Django 5.2.12 on 2026-05-05 17:43

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_analisis", models.DateField()),
                ("version_carga", models.DecimalField(decimal_places=1, max_digits=4)),
                ("origen", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completo", "Completo"),
                            ("Incompleto", "Incompleto"),
                        ],
                        default="Incompleto",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("creado_en", models.DateTimeField()),
                ("actualizado", models.DateTimeField()),
            ],
            options={
                "db_table": "reliability_acacarga",
                "ordering": ["-fecha_analisis", "-creado_en"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cargo", models.CharField(max_length=150)),
                ("area", models.CharField(max_length=150)),
                ("jefatura", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "reliability_cargo",
                "ordering": ["nombre_cargo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reliability_componente",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("tipo_funcional", models.CharField(max_length=20)),
                ("tipo_dato", models.CharField(max_length=20)),
                (
                    "tipo_calculo",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("config_calculo", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reliability_dimension",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("campo", models.CharField(max_length=120)),
                ("tipo", models.CharField(max_length=20)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "reliability_dimensioncatalogo",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        max_length=50,
                    ),
                ),
                ("logo", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "db_table": "reliability_empresa",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_equipo", models.CharField(max_length=100)),
                ("nombre_equipo", models.CharField(max_length=200)),
                ("ut", models.CharField(max_length=200)),
                ("descripcion_ut", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "reliability_equipo",
                "ordering": ["tag_equipo", "nombre_equipo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalaUnificada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.PositiveIntegerField(unique=True)),
                ("significado", models.CharField(max_length=100)),
                ("interpretacion", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "reliability_escalaunificada",
                "ordering": ["nivel"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metodologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("abreviatura", models.CharField(max_length=20)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reliability_metodologia",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("correo_corporativo", models.EmailField(max_length=254)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        db_column="auth_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="perfil_reliability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cargo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios",
                        to="core.cargo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_column="empresa_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_usuario",
                "ordering": ["nombre_completo"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Criticidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escenario_falla", models.TextField(blank=True)),
                (
                    "frecuencia_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "frecuencia_normalizada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_cons_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("indicador_criticidad", models.CharField(max_length=100)),
                (
                    "valor_criticidad_equipo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("criticidad_final", models.CharField(max_length=30)),
                ("creado_en", models.DateTimeField()),
                (
                    "aca_carga",
                    models.ForeignKey(
                        db_column="aca_carga_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.acacarga",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="equipo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_criticidad",
                "ordering": ["-creado_en", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoColumna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_columna", models.CharField(max_length=150)),
                ("clave_interna", models.CharField(max_length=100)),
                ("tipo_dato", models.CharField(max_length=20)),
                ("orden", models.PositiveIntegerField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        db_column="catalogo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="columnas",
                        to="core.dimensioncatalogo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogocolumna",
                "ordering": ["catalogo_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoFila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=255)),
                ("orden", models.PositiveIntegerField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        db_column="catalogo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filas",
                        to="core.dimensioncatalogo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogofila",
                "ordering": ["catalogo_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionCatalogoCelda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                (
                    "columna",
                    models.ForeignKey(
                        db_column="columna_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.dimensioncatalogocolumna",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        db_column="fila_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.dimensioncatalogofila",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_dimensioncatalogocelda",
                "ordering": ["fila_id", "columna_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComponenteEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "componente",
                    models.ForeignKey(
                        db_column="componente_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="componentes_equipo",
                        to="core.componente",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="componentes",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_componenteequipo",
                "ordering": ["equipo_id", "componente_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Estrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("version", models.DecimalField(decimal_places=1, max_digits=4)),
                ("activa", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="estrategias",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_estrategia",
                "ordering": ["empresa__nombre", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="acacarga",
            name="estrategia",
            field=models.ForeignKey(
                db_column="estrategia_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas_aca",
                to="core.estrategia",
            ),
        ),
        migrations.CreateModel(
            name="EstrategiaDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                ("obligatorio", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "dimension",
                    models.ForeignKey(
                        db_column="dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="estrategias_dimension",
                        to="core.dimension",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dimensiones_estrategia",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_estrategiadimension",
                "ordering": ["estrategia_id", "orden"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalaValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_ordinal", models.PositiveIntegerField()),
                (
                    "valor_numerico",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=20)),
                (
                    "escala_unificada",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_unificada_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores",
                        to="core.escalaunificada",
                    ),
                ),
                (
                    "estrategia_dimension",
                    models.ForeignKey(
                        db_column="estrategia_dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="escalas_valor",
                        to="core.estrategiadimension",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_escalavalor",
                "ordering": ["estrategia_dimension_id", "nivel_ordinal"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dimensioncatalogo",
            name="estrategia_dimension",
            field=models.OneToOneField(
                db_column="estrategia_dimension_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="catalogo",
                to="core.estrategiadimension",
            ),
        ),
        migrations.CreateModel(
            name="CriticidadDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_numerico",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_secundario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "criticidad",
                    models.ForeignKey(
                        db_column="criticidad_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dimensiones",
                        to="core.criticidad",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        db_column="dimension_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades_dimension",
                        to="core.dimension",
                    ),
                ),
                (
                    "catalogo_fila",
                    models.ForeignKey(
                        blank=True,
                        db_column="catalogo_fila_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.dimensioncatalogofila",
                    ),
                ),
                (
                    "escala_unificada",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_unificada_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.escalaunificada",
                    ),
                ),
                (
                    "escala_valor",
                    models.ForeignKey(
                        blank=True,
                        db_column="escala_valor_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.escalavalor",
                    ),
                ),
                (
                    "estrategia_dimension",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_dimension_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="criticidades",
                        to="core.estrategiadimension",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_criticidaddimension",
                "ordering": ["criticidad_id", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatrizRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_creado", models.DateField()),
                ("eje_horizontal", models.CharField(max_length=20)),
                ("leyenda_json", models.TextField(blank=True)),
                (
                    "dimension_impacto",
                    models.ForeignKey(
                        blank=True,
                        db_column="dimension_impacto_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_impacto",
                        to="core.estrategiadimension",
                    ),
                ),
                (
                    "dimension_probabilidad",
                    models.ForeignKey(
                        blank=True,
                        db_column="dimension_probabilidad_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_probabilidad",
                        to="core.estrategiadimension",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matrices_riesgo",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_matrizriesgo",
                "ordering": ["-fecha_creado", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(max_length=255)),
                ("orden_visual", models.PositiveIntegerField()),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="niveles_impacto",
                        to="core.matrizriesgo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_nivelesimpacto",
                "ordering": ["matriz_id", "orden_visual"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelProbabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(max_length=255)),
                ("orden_visual", models.PositiveIntegerField()),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="niveles_probabilidad",
                        to="core.matrizriesgo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_nivelesprobabilidad",
                "ordering": ["matriz_id", "orden_visual"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatrizRiesgoCelda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clasificacion", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=20)),
                ("resultado_num", models.DecimalField(decimal_places=2, max_digits=10)),
                ("calcular", models.BooleanField(default=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        db_column="matriz_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.matrizriesgo",
                    ),
                ),
                (
                    "impacto_nivel",
                    models.ForeignKey(
                        db_column="impacto_nivel_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.nivelimpacto",
                    ),
                ),
                (
                    "probabilidad",
                    models.ForeignKey(
                        db_column="probabilidad_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="celdas",
                        to="core.nivelprobabilidad",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_matrizriesgocelda",
                "ordering": ["matriz_id", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_servicio", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("en_curso", "En curso"),
                            ("cerrado", "Cerrado"),
                            ("pausado", "Pausado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios",
                        to="core.empresa",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_servicio",
                "ordering": ["-creado_en", "codigo_servicio"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="acacarga",
            name="servicio",
            field=models.ForeignKey(
                db_column="servicio_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas_aca",
                to="core.servicio",
            ),
        ),
        migrations.CreateModel(
            name="ServicioEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicios_equipo",
                        to="core.equipo",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="equipos_servicio",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_servicioequipo",
                "ordering": ["servicio_id", "equipo_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicioMetodologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodologia",
                    models.ForeignKey(
                        db_column="metodologia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicio_metodologias",
                        to="core.metodologia",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="servicio_metodologias",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_serviciometodologia",
                "ordering": ["servicio_id", "metodologia_id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="servicio",
            name="metodologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="servicios",
                through="core.ServicioMetodologia",
                to="core.metodologia",
            ),
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sistema", models.CharField(max_length=200)),
                ("codigo_sistema", models.CharField(max_length=100)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sistemas",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_sistemas",
                "ordering": ["empresa__nombre", "nombre_sistema"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="equipo",
            name="sistema",
            field=models.ForeignKey(
                db_column="sistema_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipos",
                to="core.sistema",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="creado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por_usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="responsable_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="responsable_usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios_responsables",
                to="core.usuario",
            ),
        ),
        migrations.CreateModel(
            name="InicioSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.DateTimeField()),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inicios_sesion",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_iniciosesion",
                "ordering": ["-hora"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccesoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puede_ver", models.BooleanField(default=True)),
                ("puede_editar", models.BooleanField(default=False)),
                ("puede_ver_todo", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.empresa",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        blank=True,
                        db_column="estrategia_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.estrategia",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="servicio_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.servicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accesos",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_accesousuario",
                "ordering": ["-creado_en"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="acacarga",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cargas_aca",
                to="core.usuario",
            ),
        ),
        migrations.CreateModel(
            name="UsuarioEliminado",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="archivo_eliminacion",
                        serialize=False,
                        to="core.usuario",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("correo_corporativo", models.EmailField(blank=True, max_length=254)),
                ("eliminado_en", models.DateTimeField()),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "auth_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="auth_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios_eliminados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cargo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios_eliminados",
                        to="core.cargo",
                    ),
                ),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="eliminado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="eliminaciones_de_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_column="empresa_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios_eliminados",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_usuario_eliminado",
                "ordering": ["-eliminado_en", "nombre_completo"],
                "abstract": False,
            },
        ),
    ]
