# Generated by Django 5.2.12 on 2026-07-01 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="criticidad",
            name="matriz",
            field=models.ForeignKey(
                blank=True,
                db_column="matriz_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criticidades_aca",
                to="core.matrizriesgo",
            ),
        ),
        migrations.AddField(
            model_name="criticidad",
            name="matriz_celda",
            field=models.ForeignKey(
                blank=True,
                db_column="matriz_celda_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criticidades_aca",
                to="core.matrizriesgocelda",
            ),
        ),
    ]
