# Generated by Django 5.2.12 on 2026-05-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorNivelJerarquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_nivel_jerarquia",
                        to="core.empresa",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        db_column="nivel_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_simples",
                        to="core.niveljerarquia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_valorniveljerarquia",
                "ordering": [
                    "empresa__nombre",
                    "nivel__orden",
                    "orden",
                    "codigo",
                    "nombre",
                ],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["empresa", "nivel", "activo"],
                        name="reliability_empresa_adb48d_idx",
                    ),
                    models.Index(
                        fields=["codigo"], name="reliability_codigo_4aed8b_idx"
                    ),
                    models.Index(
                        fields=["nombre"], name="reliability_nombre_486f11_idx"
                    ),
                ],
                "unique_together": {("empresa", "nivel", "codigo")},
            },
        ),
    ]
