# Generated by Django 5.2.12 on 2026-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acacarga_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="status",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("en_curso", "En curso"),
                    ("cerrado", "Cerrado"),
                    ("pausado", "Pausado"),
                ],
                default="activo",
                max_length=20,
            ),
        ),
    ]
