# Generated by Django 5.2.12 on 2026-05-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_valorniveljerarquia"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamiliaEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField()),
                ("actualizado", models.DateTimeField()),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="familias_equipo",
                        to="core.servicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="familias_equipo",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_familiaequipo",
                "ordering": ["servicio_id", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamiliaEquipoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "equipo",
                    models.ForeignKey(
                        db_column="equipo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="familias_item",
                        to="core.equipo",
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        db_column="familia_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.familiaequipo",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_familiaequipoitem",
                "ordering": [
                    "familia_id",
                    "orden",
                    "equipo__tag_equipo",
                    "equipo__nombre_equipo",
                ],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="familiaequipo",
            index=models.Index(
                fields=["servicio", "activa"], name="idx_familiaequipo_servicio"
            ),
        ),
        migrations.AddIndex(
            model_name="familiaequipo",
            index=models.Index(fields=["nombre"], name="idx_familiaequipo_nombre"),
        ),
        migrations.AlterUniqueTogether(
            name="familiaequipo",
            unique_together={("servicio", "nombre")},
        ),
        migrations.AddIndex(
            model_name="familiaequipoitem",
            index=models.Index(fields=["familia"], name="idx_familiaitem_familia"),
        ),
        migrations.AddIndex(
            model_name="familiaequipoitem",
            index=models.Index(fields=["equipo"], name="idx_familiaitem_equipo"),
        ),
        migrations.AlterUniqueTogether(
            name="familiaequipoitem",
            unique_together={("familia", "equipo")},
        ),
    ]
