# Generated by Django 5.2.12 on 2026-05-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_familiaequipo_familiaequipoitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscenarioFalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField()),
                ("actualizado", models.DateTimeField()),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="escenarios_falla",
                        to="core.servicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="escenarios_falla",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_escenariofalla",
                "ordering": ["servicio_id", "nombre"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["servicio", "activo"],
                        name="idx_escenariofalla_servicio",
                    ),
                    models.Index(fields=["nombre"], name="idx_escenariofalla_nombre"),
                ],
                "unique_together": {("servicio", "nombre")},
            },
        ),
    ]
