# Generated by Django 6.0.6 on 2026-07-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_componente_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="area",
            field=models.CharField(max_length=150, verbose_name="Área"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="jefatura",
            field=models.CharField(max_length=150, verbose_name="Jefatura"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="nombre_cargo",
            field=models.CharField(max_length=150, verbose_name="Nombre del cargo"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="codigo_servicio",
            field=models.CharField(max_length=100, verbose_name="Código del servicio"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="estrategia",
            field=models.ForeignKey(
                blank=True,
                db_column="estrategia_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios",
                to="core.estrategia",
                verbose_name="Estrategia",
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="status",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("en_curso", "En curso"),
                    ("cerrado", "Cerrado"),
                    ("pausado", "Pausado"),
                ],
                default="activo",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
