# Generated by Django 5.2.12 on 2026-05-26 16:47

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_escenariofalla"),
    ]

    operations = [
        migrations.AddField(
            model_name="criticidad",
            name="observacion",
            field=models.TextField(blank=True, default="", verbose_name="Observación"),
        ),
        migrations.AddField(
            model_name="rcm",
            name="observacion",
            field=models.TextField(blank=True, default="", verbose_name="Observación"),
        ),
        migrations.CreateModel(
            name="CriticidadAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=core.models.aca_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("creado_en", models.DateTimeField()),
                (
                    "criticidad",
                    models.ForeignKey(
                        db_column="criticidad_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="core.criticidad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjuntos_aca",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_criticidadadjunto",
                "ordering": ["-creado_en", "-id"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["criticidad"], name="idx_critadj_criticidad"),
                    models.Index(fields=["creado_en"], name="idx_critadj_creado"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RCMAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=core.models.rcm_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("creado_en", models.DateTimeField()),
                (
                    "rcm",
                    models.ForeignKey(
                        db_column="rcm_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="core.rcm",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjuntos_rcm",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_rcmadjunto",
                "ordering": ["-creado_en", "-id"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["rcm"], name="idx_rcmadj_rcm"),
                    models.Index(fields=["creado_en"], name="idx_rcmadj_creado"),
                ],
            },
        ),
    ]
