# Generated by Django 5.2.12 on 2026-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_criticidad_observacion_rcm_observacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estrategiadimension",
            name="considerar_avance_aca",
            field=models.BooleanField(
                default=True, verbose_name="Considerar en avance ACA"
            ),
        ),
    ]
