# Generated by Django 5.2.12 on 2026-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_estrategiadimension_considerar_avance_aca"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioncatalogocolumna",
            name="visible_en_registro",
            field=models.BooleanField(default=True, verbose_name="Visible en registro"),
        ),
    ]
