# Generated by Django 5.2.12 on 2026-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_carga_common_for_rcm"),
    ]

    operations = [
        migrations.AddField(
            model_name="estrategiadimension",
            name="proceso_uso",
            field=models.CharField(
                choices=[("aca", "ACA"), ("rcm", "RCM"), ("ambos", "ACA y RCM")],
                default="aca",
                max_length=10,
            ),
        ),
    ]
