# Generated by Django 5.2.12 on 2026-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dimensioncatalogocolumna_visible_en_registro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estrategiadimension",
            name="proceso_uso",
            field=models.CharField(
                choices=[("aca", "ACA"), ("fmeca", "FMECA"), ("ambos", "ACA y FMECA")],
                default="aca",
                max_length=10,
            ),
        ),
    ]
