# Generated by Django 5.2.12 on 2026-05-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_estrategiadimension_proceso_uso"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fmea_fmeca",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveIndex(
            model_name="fmea_fmeca",
            name="idx_fmea_severidad",
        ),
        migrations.RemoveIndex(
            model_name="fmea_fmeca",
            name="idx_fmea_ocurrencia",
        ),
        migrations.RemoveIndex(
            model_name="fmea_fmeca",
            name="idx_fmea_deteccion",
        ),
        migrations.RemoveIndex(
            model_name="fmea_fmeca",
            name="idx_fmea_npr",
        ),
        migrations.RemoveField(
            model_name="fmea_fmeca",
            name="deteccion",
        ),
        migrations.RemoveField(
            model_name="fmea_fmeca",
            name="npr",
        ),
        migrations.RemoveField(
            model_name="fmea_fmeca",
            name="ocurrencia",
        ),
        migrations.RemoveField(
            model_name="fmea_fmeca",
            name="severidad",
        ),
    ]
