# Generated by Django 5.2.12 on 2026-05-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_fmea_fmeca_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacionfmea",
            name="catalogo_fila",
            field=models.ForeignKey(
                blank=True,
                db_column="catalogo_fila_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="evaluaciones_fmea",
                to="core.dimensioncatalogofila",
            ),
        ),
        migrations.AddField(
            model_name="evaluacionfmea",
            name="escala_valor",
            field=models.ForeignKey(
                blank=True,
                db_column="escala_valor_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="evaluaciones_fmea",
                to="core.escalavalor",
            ),
        ),
        migrations.AddField(
            model_name="evaluacionfmea",
            name="valor_texto",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="evaluacionfmea",
            name="valor_numerico",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
