# Generated by Django 5.2.12 on 2026-05-11 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_evaluacionfmea_catalogo_fila_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoTareaRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=150)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("reemplazado", "Reemplazado"),
                            ("eliminado", "Eliminado"),
                        ],
                        default="activo",
                        max_length=30,
                    ),
                ),
                (
                    "fmea",
                    models.ForeignKey(
                        db_column="fmea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="grupos_tarea",
                        to="core.fmea_fmeca",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_grupo_tarea_rcm",
                "ordering": ["fmea_id", "orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTareaEstrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(max_length=80)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tipos_tarea",
                        to="core.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_tipo_tarea_estrategia",
                "ordering": ["estrategia_id", "orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTareaUnificada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.SlugField(max_length=80, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "reliability_tipo_tarea_unificada",
                "ordering": ["orden", "nombre"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["codigo"], name="idx_ttu_codigo"),
                    models.Index(fields=["activo"], name="idx_ttu_activo"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TareaRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("tactica", models.CharField(blank=True, max_length=100)),
                ("limite_aceptable", models.TextField(blank=True)),
                ("parametros", models.TextField(blank=True)),
                ("riesgo_material", models.TextField(blank=True)),
                ("especialidad", models.CharField(blank=True, max_length=100)),
                ("puesto_trabajo", models.CharField(blank=True, max_length=100)),
                ("estado_equipo", models.CharField(blank=True, max_length=100)),
                (
                    "frecuencia_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("frecuencia_unidad", models.CharField(blank=True, max_length=50)),
                ("frecuencia_texto", models.CharField(blank=True, max_length=150)),
                (
                    "duracion_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duracion_hr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cantidad_personas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("plan_sap", models.CharField(blank=True, max_length=100)),
                ("descripcion_plan", models.TextField(blank=True)),
                ("hoja_ruta", models.CharField(blank=True, max_length=100)),
                ("texto_hoja_ruta", models.TextField(blank=True)),
                ("operacion_hoja_ruta", models.CharField(blank=True, max_length=100)),
                ("texto_operacion", models.TextField(blank=True)),
                ("operacion_pauta", models.CharField(blank=True, max_length=100)),
                ("pauta", models.CharField(blank=True, max_length=150)),
                ("titulo_pauta", models.TextField(blank=True)),
                ("repuesto", models.TextField(blank=True)),
                ("componente_involucrado", models.TextField(blank=True)),
                ("numero_parte", models.CharField(blank=True, max_length=100)),
                ("numero_sap", models.CharField(blank=True, max_length=100)),
                ("procedimiento_trabajo", models.TextField(blank=True)),
                (
                    "costo_hh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_repuestos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tarifa_servicios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("oportunidad_mejora", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("reemplazado", "Reemplazado"),
                            ("eliminado", "Eliminado"),
                        ],
                        default="activo",
                        max_length=30,
                    ),
                ),
                (
                    "fmea",
                    models.ForeignKey(
                        db_column="fmea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas_rcm",
                        to="core.fmea_fmeca",
                    ),
                ),
                (
                    "grupo_tarea",
                    models.ForeignKey(
                        blank=True,
                        db_column="grupo_tarea_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas",
                        to="core.grupotarearcm",
                    ),
                ),
                (
                    "tipo_tarea_estrategia",
                    models.ForeignKey(
                        db_column="tipo_tarea_estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas_rcm",
                        to="core.tipotareaestrategia",
                    ),
                ),
                (
                    "tipo_tarea_unificada",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipo_tarea_unificada_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tareas_rcm",
                        to="core.tipotareaunificada",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_tarea_rcm",
                "ordering": ["fmea_id", "orden", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="grupotarearcm",
            name="tipo_tarea_unificada",
            field=models.ForeignKey(
                blank=True,
                db_column="tipo_tarea_unificada_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="grupos_rcm",
                to="core.tipotareaunificada",
            ),
        ),
        migrations.CreateModel(
            name="EquivalenciaTipoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_tarea_estrategia",
                    models.ForeignKey(
                        db_column="tipo_tarea_estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="equivalencias",
                        to="core.tipotareaestrategia",
                    ),
                ),
                (
                    "tipo_tarea_unificada",
                    models.ForeignKey(
                        db_column="tipo_tarea_unificada_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="equivalencias",
                        to="core.tipotareaunificada",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_equivalencia_tipo_tarea",
                "ordering": ["tipo_tarea_estrategia_id", "tipo_tarea_unificada_id"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["estrategia"], name="idx_tte_estrategia"),
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["codigo"], name="idx_tte_codigo"),
        ),
        migrations.AddIndex(
            model_name="tipotareaestrategia",
            index=models.Index(fields=["activo"], name="idx_tte_activo"),
        ),
        migrations.AddConstraint(
            model_name="tipotareaestrategia",
            constraint=models.UniqueConstraint(
                fields=("estrategia", "codigo"), name="uniq_tte_estrategia_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["fmea"], name="idx_trcm_fmea"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["grupo_tarea"], name="idx_trcm_grupo"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(
                fields=["tipo_tarea_estrategia"], name="idx_trcm_tipo_estrat"
            ),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(
                fields=["tipo_tarea_unificada"], name="idx_trcm_tipo_unif"
            ),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["estado"], name="idx_trcm_estado"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["plan_sap"], name="idx_trcm_plan_sap"),
        ),
        migrations.AddIndex(
            model_name="tarearcm",
            index=models.Index(fields=["hoja_ruta"], name="idx_trcm_hoja_ruta"),
        ),
        migrations.AddIndex(
            model_name="grupotarearcm",
            index=models.Index(fields=["fmea"], name="idx_gtr_fmea"),
        ),
        migrations.AddIndex(
            model_name="grupotarearcm",
            index=models.Index(
                fields=["tipo_tarea_unificada"], name="idx_gtr_tipo_unificada"
            ),
        ),
        migrations.AddIndex(
            model_name="grupotarearcm",
            index=models.Index(fields=["estado"], name="idx_gtr_estado"),
        ),
        migrations.AddIndex(
            model_name="equivalenciatipotarea",
            index=models.Index(
                fields=["tipo_tarea_estrategia"], name="idx_ett_tipo_estrategia"
            ),
        ),
        migrations.AddIndex(
            model_name="equivalenciatipotarea",
            index=models.Index(
                fields=["tipo_tarea_unificada"], name="idx_ett_tipo_unificada"
            ),
        ),
        migrations.AddIndex(
            model_name="equivalenciatipotarea",
            index=models.Index(fields=["activo"], name="idx_ett_activo"),
        ),
        migrations.AddConstraint(
            model_name="equivalenciatipotarea",
            constraint=models.UniqueConstraint(
                fields=("tipo_tarea_estrategia", "tipo_tarea_unificada"),
                name="uniq_equiv_tipo_tarea",
            ),
        ),
    ]
