# Generated by Django 5.2.12 on 2026-05-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_grupotarearcm_tipotareaestrategia_tipotareaunificada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampoTareaEstrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("clave", models.SlugField(max_length=100)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("texto_largo", "Texto largo"),
                            ("numero", "Número entero"),
                            ("decimal", "Número decimal"),
                            ("fecha", "Fecha"),
                            ("booleano", "Sí/No"),
                            ("opcion", "Opción"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                (
                    "campo_sistema",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Sin mapeo"),
                            ("descripcion", "Descripción"),
                            ("tactica", "Táctica"),
                            ("limite_aceptable", "Límite aceptable"),
                            ("parametros", "Parámetros"),
                            ("riesgo_material", "Riesgo material"),
                            ("especialidad", "Especialidad"),
                            ("puesto_trabajo", "Puesto de trabajo"),
                            ("estado_equipo", "Estado equipo"),
                            ("frecuencia_valor", "Frecuencia valor"),
                            ("frecuencia_unidad", "Frecuencia unidad"),
                            ("frecuencia_texto", "Frecuencia texto"),
                            ("duracion_min", "Duración min"),
                            ("duracion_hr", "Duración hr"),
                            ("cantidad_personas", "Cantidad personas"),
                            ("hh", "HH"),
                            ("plan_sap", "Plan SAP"),
                            ("descripcion_plan", "Descripción plan"),
                            ("hoja_ruta", "Hoja ruta"),
                            ("texto_hoja_ruta", "Texto hoja ruta"),
                            ("operacion_hoja_ruta", "Operación hoja ruta"),
                            ("texto_operacion", "Texto operación"),
                            ("operacion_pauta", "Operación pauta"),
                            ("pauta", "Pauta"),
                            ("titulo_pauta", "Título pauta"),
                            ("repuesto", "Repuesto"),
                            ("componente_involucrado", "Componente involucrado"),
                            ("numero_parte", "Número parte"),
                            ("numero_sap", "Número SAP"),
                            ("procedimiento_trabajo", "Procedimiento trabajo"),
                            ("costo_hh", "Costo HH"),
                            ("costo_repuestos", "Costo repuestos"),
                            ("tarifa_servicios", "Tarifa servicios"),
                            ("costo_total", "Costo total"),
                            ("oportunidad_mejora", "Oportunidad mejora"),
                        ],
                        max_length=80,
                    ),
                ),
                ("opciones_json", models.TextField(blank=True)),
                ("obligatorio", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_tarea_estrategia",
                    models.ForeignKey(
                        db_column="tipo_tarea_estrategia_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="campos",
                        to="core.tipotareaestrategia",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_campo_tarea_estrategia",
                "ordering": ["tipo_tarea_estrategia_id", "orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValorCampoTareaRCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                ("valor_fecha", models.DateField(blank=True, null=True)),
                (
                    "campo",
                    models.ForeignKey(
                        db_column="campo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_tarea",
                        to="core.campotareaestrategia",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        db_column="tarea_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="valores_campos",
                        to="core.tarearcm",
                    ),
                ),
            ],
            options={
                "db_table": "reliability_valor_campo_tarea_rcm",
                "ordering": ["tarea_id", "campo__orden", "campo_id"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(
                fields=["tipo_tarea_estrategia"], name="idx_cte_tipo_tarea"
            ),
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(fields=["clave"], name="idx_cte_clave"),
        ),
        migrations.AddIndex(
            model_name="campotareaestrategia",
            index=models.Index(fields=["activo"], name="idx_cte_activo"),
        ),
        migrations.AddConstraint(
            model_name="campotareaestrategia",
            constraint=models.UniqueConstraint(
                fields=("tipo_tarea_estrategia", "clave"), name="uniq_cte_tipo_clave"
            ),
        ),
        migrations.AddIndex(
            model_name="valorcampotarearcm",
            index=models.Index(fields=["tarea"], name="idx_vctr_tarea"),
        ),
        migrations.AddIndex(
            model_name="valorcampotarearcm",
            index=models.Index(fields=["campo"], name="idx_vctr_campo"),
        ),
        migrations.AddConstraint(
            model_name="valorcampotarearcm",
            constraint=models.UniqueConstraint(
                fields=("tarea", "campo"), name="uniq_valor_tarea_campo"
            ),
        ),
    ]
