# Generated by Django 5.2.12 on 2026-06-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rcm_funcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="creado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="creado_por_usuario_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="servicios_creados",
                to="core.usuario",
                verbose_name="Responsable",
            ),
        ),
    ]
