# Generated by Django 5.2.12 on 2026-05-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_campotareaestrategia_valorcampotarearcm_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equivalenciatipotarea",
            name="uniq_equiv_tipo_tarea",
        ),
        migrations.RemoveIndex(
            model_name="equivalenciatipotarea",
            name="idx_ett_tipo_estrategia",
        ),
        migrations.RemoveIndex(
            model_name="equivalenciatipotarea",
            name="idx_ett_tipo_unificada",
        ),
        migrations.RemoveIndex(
            model_name="equivalenciatipotarea",
            name="idx_ett_activo",
        ),
        migrations.RemoveIndex(
            model_name="grupotarearcm",
            name="idx_gtr_fmea",
        ),
        migrations.RemoveIndex(
            model_name="grupotarearcm",
            name="idx_gtr_tipo_unificada",
        ),
        migrations.RemoveIndex(
            model_name="grupotarearcm",
            name="idx_gtr_estado",
        ),
        migrations.RemoveField(
            model_name="equivalenciatipotarea",
            name="tipo_tarea_estrategia",
        ),
        migrations.RemoveField(
            model_name="equivalenciatipotarea",
            name="tipo_tarea_unificada",
        ),
        migrations.RemoveField(
            model_name="grupotarearcm",
            name="fmea",
        ),
        migrations.RemoveField(
            model_name="grupotarearcm",
            name="tipo_tarea_unificada",
        ),
        migrations.RemoveIndex(
            model_name="tarearcm",
            name="idx_trcm_grupo",
        ),
        migrations.RemoveIndex(
            model_name="tarearcm",
            name="idx_trcm_tipo_unif",
        ),
        migrations.RemoveField(
            model_name="tarearcm",
            name="grupo_tarea",
        ),
        migrations.RemoveField(
            model_name="tarearcm",
            name="tipo_tarea_unificada",
        ),
        migrations.RemoveField(
            model_name="campotareaestrategia",
            name="campo_sistema",
        ),
        migrations.DeleteModel(
            name="EquivalenciaTipoTarea",
        ),
        migrations.DeleteModel(
            name="GrupoTareaRCM",
        ),
        migrations.DeleteModel(
            name="TipoTareaUnificada",
        ),
    ]
