# Generated by Django 5.2.12 on 2026-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_estrategiadimension_fmeca_progress_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviciometodologia",
            name="metodologia",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="metodologias",
        ),
        migrations.RemoveField(
            model_name="serviciometodologia",
            name="servicio",
        ),
        migrations.DeleteModel(
            name="Metodologia",
        ),
        migrations.DeleteModel(
            name="ServicioMetodologia",
        ),
    ]
