from collections import OrderedDict
from . import models
from .forms import EmpresaForm, EquipoForm, ServicioForm

MODEL_REGISTRY = OrderedDict({
    'empresa': {
        'model': models.Empresa,
        'label': 'Empresas',
        'group': 'Configuración',
        'form_class': EmpresaForm,
        'search_fields': ['nombre', 'sigla', 'estado'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },

    'metodologia': {
        'model': models.Metodologia,
        'label': 'Metodologías',
        'group': 'Configuración',
        'search_fields': ['nombre', 'abreviatura', 'descripcion'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'cargo': {
        'model': models.Cargo,
        'label': 'Cargos',
        'group': 'Configuración',
        'search_fields': ['nombre_cargo', 'area', 'jefatura'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'usuario': {
        'model': models.Usuario,
        'label': 'Usuarios',
        'group': 'Configuración',
        'search_fields': ['nombre_completo', 'correo_corporativo'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'componente': {
        'model': models.Componente,
        'label': 'Componentes',
        'group': 'Configuración',
        'search_fields': ['nombre', 'descripcion'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'equipo': {
        'model': models.Equipo,
        'label': 'Equipos',
        'group': 'Operación',
        'form_class': EquipoForm,
        'search_fields': ['tag_equipo', 'nombre_equipo', 'ut', 'descripcion_ut'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'niveljerarquia': {
        'model': models.NivelJerarquia,
        'label': 'Niveles jerarquia UT',
        'group': 'Configuración',
        'search_fields': ['nombre'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'nodojerarquia': {
        'model': models.NodoJerarquia,
        'label': 'Nodos jerarquia UT',
        'group': 'Configuración',
        'search_fields': ['codigo', 'nombre'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'dimension': {
        'model': models.Dimension,
        'label': 'Dimensiones',
        'group': 'Configuración',
        'search_fields': ['nombre', 'descripcion', 'tipo_funcional', 'tipo_dato'],
        'show_in_sidebar': True,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'escalaunificada': {
        'model': models.EscalaUnificada,
        'label': 'Escala unificada',
        'group': 'Configuración',
        'search_fields': ['significado', 'interpretacion'],
        'show_in_sidebar': True,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'estrategia': {
        'model': models.Estrategia,
        'label': 'Estrategias',
        'group': 'Operación',
        'search_fields': ['nombre', 'descripcion'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'servicio': {
        'model': models.Servicio,
        'label': 'Servicios',
        'group': 'Operación',
        'form_class': ServicioForm,
        'search_fields': ['codigo_servicio', 'descripcion', 'status'],
        'show_in_sidebar': False,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'accesousuario': {
        'model': models.AccesoUsuario,
        'label': 'Accesos usuario',
        'group': 'Operación',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'servicioequipo': {
        'model': models.ServicioEquipo,
        'label': 'Servicio - Equipo',
        'group': 'Operación',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'rcm': {
        'model': models.RCM,
        'label': 'Registros RCM',
        'group': 'RCM/FMEA',
        'search_fields': ['falla_funcional', 'modo_de_falla', 'causa', 'efecto', 'estado'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'fmea_fmeca': {
        'model': models.FMEA_FMECA,
        'label': 'FMEA/FMECA',
        'group': 'RCM/FMEA',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'evaluacionfmea': {
        'model': models.EvaluacionFMEA,
        'label': 'Evaluaciones FMEA',
        'group': 'RCM/FMEA',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'componenteequipo': {
        'model': models.ComponenteEquipo,
        'label': 'Componente - Equipo',
        'group': 'Operación',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'carga': {
        'model': models.Carga,
        'label': 'Cargas',
        'group': 'Operación',
        'search_fields': ['origen', 'status'],
        'show_in_sidebar': False,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'criticidad': {
        'model': models.Criticidad,
        'label': 'Criticidades',
        'group': 'Operación',
        'search_fields': ['indicador_criticidad', 'criticidad_final', 'escenario_falla'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'criticidaddimension': {
        'model': models.CriticidadDimension,
        'label': 'Criticidad - Dimensión',
        'group': 'Operación',
        'search_fields': ['valor_texto'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'iniciosesion': {
        'model': models.InicioSesion,
        'label': 'Inicio de sesión',
        'group': 'Operación',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'estrategiadimension': {
        'model': models.EstrategiaDimension,
        'label': 'Estrategia - Dimensión',
        'group': 'Catálogos y escalas',
        'search_fields': [],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'dimensioncatalogo': {
        'model': models.DimensionCatalogo,
        'label': 'Catálogos de dimensión',
        'group': 'Catálogos y escalas',
        'search_fields': ['nombre', 'campo', 'tipo', 'descripcion'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'dimensioncatalogofila': {
        'model': models.DimensionCatalogoFila,
        'label': 'Filas de catálogo',
        'group': 'Catálogos y escalas',
        'search_fields': ['etiqueta'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'dimensioncatalogocolumna': {
        'model': models.DimensionCatalogoColumna,
        'label': 'Columnas de catálogo',
        'group': 'Catálogos y escalas',
        'search_fields': ['nombre_columna', 'clave_interna', 'tipo_dato'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'dimensioncatalogocelda': {
        'model': models.DimensionCatalogoCelda,
        'label': 'Celdas de catálogo',
        'group': 'Catálogos y escalas',
        'search_fields': ['valor_texto'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'escalavalor': {
        'model': models.EscalaValor,
        'label': 'Escalas valor',
        'group': 'Catálogos y escalas',
        'search_fields': ['codigo', 'descripcion', 'color'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'matrizriesgo': {
        'model': models.MatrizRiesgo,
        'label': 'Matrices de riesgo',
        'group': 'Matrices',
        'search_fields': ['nombre', 'eje_horizontal', 'leyenda_json'],
        'show_in_sidebar': True,
        'show_in_dashboard': True,
        'allow_direct_crud': True,
        'delete_superuser_only': True,
    },
    'nivelimpacto': {
        'model': models.NivelImpacto,
        'label': 'Niveles de impacto',
        'group': 'Matrices',
        'search_fields': ['nombre', 'descripcion'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'nivelprobabilidad': {
        'model': models.NivelProbabilidad,
        'label': 'Niveles de probabilidad',
        'group': 'Matrices',
        'search_fields': ['nombre', 'descripcion'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
    'matrizriesgocelda': {
        'model': models.MatrizRiesgoCelda,
        'label': 'Celdas de matriz',
        'group': 'Matrices',
        'search_fields': ['clasificacion', 'color'],
        'show_in_sidebar': False,
        'show_in_dashboard': False,
        'allow_direct_crud': False,
        'delete_superuser_only': True,
    },
})


def get_registered_model(model_key: str):
    return MODEL_REGISTRY.get(model_key)
